---
- name: Deploy my web app
  hosts: all
  become: yes
  tasks:
    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Install rsync
      apt:
        name: rsync
        state: present

    - name: Sync files to server
      synchronize:
        src: ../
        dest: /var/www/devops-test
        recursive: yes
        delete: yes

    - name: Set permissions on web directory
      file:
        path: /var/www/devops-test
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Test Nginx configuration
      command: nginx -t
      register: nginx_test
      failed_when: "'successful' not in nginx_test.stdout + nginx_test.stderr"

    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
