name: Deploy Website via Ansible

on:
  push:
    branches:
      - main # or 'master' if that's your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

          - name: Run Ansible Playbook
          run: |
            sudo apt-get update
            sudo apt-get install -y ansible

            echo "[web]" > inventory
            echo "${{ secrets.SSH_HOST }}" >> inventory

            ansible-playbook provisioning/ansible.yml \
              -i inventory \
              -u ${{ secrets.SSH_USER }} \
              --private-key ~/.ssh/id_rsa \
              -e ansible_ssh_common_args='-o StrictHostKeyChecking=no' \
              -vvv
