name: Deploy Website via Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Run Ansible Playbook
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible
        ansible-playbook provisioning/ansible.yml \
          -i "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}," \
          --private-key ~/.ssh/id_rsa
